"""
frs_loader.py  –  NumPy version
=================================
Load a preprocessed turtlebot FRS .mat file and return a plain Python dict
of NumPy arrays.

The FRS files must first be preprocessed by running preprocess_frs.m in
MATLAB, which extracts the msspoly polynomial into plain numeric arrays that
scipy can read.

Usage
-----
>>> from frs_loader import load_frs
>>> frs = load_frs(v_0=0.75)              # auto-selects file based on speed
>>> frs = load_frs(path='myfile_preproc.mat')   # explicit path
"""

import os
import numpy as np
import scipy.io


# Default location of the preprocessed FRS files
_DEFAULT_DIR = os.path.join(
    os.path.dirname(__file__),
    '..', 'python_preprocessed_frs'
)

_FRS_FILES = {
    (0.0, 0.5):  'turtlebot_FRS_deg_10_v_0_0.0_to_0.5.mat',
    (0.5, 1.0):  'turtlebot_FRS_deg_10_v_0_0.5_to_1.0.mat',
    (1.0, 1.5):  'turtlebot_FRS_deg_10_v_0_1.0_to_1.5.mat',
}


def _select_frs_filename(v_0):
    """Choose the FRS file for a given initial speed."""
    for (lo, hi), name in _FRS_FILES.items():
        if lo <= v_0 <= hi:
            return name
    raise ValueError(
        f"No FRS file for v_0={v_0:.3f} m/s. "
        "Please choose a speed in [0.0, 1.5] m/s."
    )


def load_frs(v_0=None, path=None, frs_dir=None):
    """Load a preprocessed turtlebot FRS file.

    Provide either v_0 (initial speed) for automatic file selection, or a
    direct path to a *_preproc.mat file.

    The preproc file is generated by running preprocess_frs.m in MATLAB.

    Args:
        v_0:     initial speed (m/s) in [0.0, 1.5].  Ignored when path is set.
        path:    explicit path to a *_preproc.mat file.
        frs_dir: directory containing the FRS .mat files.
                 Defaults to the RTD_tutorial reach_sets folder.

    Returns:
        frs: dict with keys:
            'pows'           : (Nterms, Nvars)  monomial powers
            'coef'           : (Nterms,)         coefficients (FRS_poly - 1)
            'z_cols'         : (Nz,)  0-indexed columns of pows for z vars
            'k_cols'         : (Nk,)  0-indexed columns of pows for k vars
            'pows_hZ0'       : (Nterms_h, Nz)   powers for the FRS boundary
            'coef_hZ0'       : (Nterms_h,)       coefficients for h_Z0
            'z_cols_hZ0'     : (Nz,)  0-indexed columns for h_Z0 z vars
            't_plan'         : planning horizon (s)
            't_f'            : total FRS time horizon (s), or None if absent
            'v_range'        : [v_lo, v_hi] speed range (m/s)
            'delta_v'        : speed bound around v_0 (m/s)
            'distance_scale' : D (m)
            'initial_x'      : x_0 (FRS frame x-origin)
            'initial_y'      : y_0 (FRS frame y-origin)
            'w_max'          : maximum yaw rate (rad/s)

    Raises:
        FileNotFoundError: if the preproc file does not exist.
    """
    if frs_dir is None:
        frs_dir = _DEFAULT_DIR

    if path is None:
        if v_0 is None:
            raise ValueError("Provide either v_0 or path.")
        basename     = _select_frs_filename(v_0)
        preproc_path = os.path.join(frs_dir, basename.replace('.mat', '_preproc.mat'))
    else:
        preproc_path = path

    if not os.path.exists(preproc_path):
        raise FileNotFoundError(
            f"Preproc file not found: {preproc_path}\n"
            "Run preprocess_frs.m in MATLAB to generate it."
        )

    return _load_preproc(preproc_path)


def _load_preproc(path):
    """Load a *_preproc.mat file (plain arrays)."""
    mat = scipy.io.loadmat(path, struct_as_record=False, squeeze_me=True)

    frs = {}

    # Polynomial data  (z_cols / k_cols are 1-indexed in MATLAB → convert)
    frs['pows']   = np.array(mat['pows'],   dtype=float)
    frs['coef']   = np.array(mat['coef'],   dtype=float).ravel()
    frs['z_cols'] = np.array(mat['z_cols'], dtype=int).ravel() - 1  # 0-indexed
    frs['k_cols'] = np.array(mat['k_cols'], dtype=int).ravel() - 1  # 0-indexed

    # h_Z0 boundary polynomial (optional)
    if 'pows_hZ0' in mat and mat['pows_hZ0'].size > 0:
        frs['pows_hZ0']   = np.array(mat['pows_hZ0'],   dtype=float)
        frs['coef_hZ0']   = np.array(mat['coef_hZ0'],   dtype=float).ravel()
        frs['z_cols_hZ0'] = np.array(mat['z_cols_hZ0'], dtype=int).ravel() - 1
    else:
        frs['pows_hZ0']   = None
        frs['coef_hZ0']   = None
        frs['z_cols_hZ0'] = None

    # Scalar metadata
    frs['t_plan']         = float(mat['t_plan'])
    frs['t_f']            = float(mat['t_f']) if 't_f' in mat else None
    frs['v_range']        = np.array(mat['v_range'], dtype=float).ravel()
    frs['delta_v']        = float(mat['delta_v'])
    frs['distance_scale'] = float(mat['distance_scale'])
    frs['initial_x']      = float(mat['initial_x'])
    frs['initial_y']      = float(mat['initial_y'])
    frs['w_max']          = float(mat['w_max'])

    return frs


# ---------------------------------------------------------------------------
# Utility: convert optimal k to physical w_des, v_des
# ---------------------------------------------------------------------------

def k_to_wv(k_opt, frs):
    """Convert trajectory parameters k to desired yaw-rate and speed.

    Uses the mapping defined in step_4_create_turtlebot_cost_function.m:
        w_des = w_max * k_1
        v_des = (v_max/2) * k_2 + (v_max/2)

    where v_max = v_range[1].

    Args:
        k_opt: (2,) array [k_1, k_2]
        frs:   FRS dict from load_frs

    Returns:
        w_des: desired yaw rate (rad/s)
        v_des: desired speed (m/s)
    """
    v_max = frs['v_range'][1]
    w_des = frs['w_max'] * float(k_opt[0])
    v_des = (v_max / 2.0) * float(k_opt[1]) + (v_max / 2.0)
    return w_des, v_des
